# Generated by Django 4.2.18 on 2025-01-25 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
    ]
