# Generated by Django 4.2.18 on 2025-01-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kindergarten',
            name='director',
        ),
        migrations.RemoveField(
            model_name='kindergarten',
            name='established_date',
        ),
        migrations.RemoveField(
            model_name='school',
            name='director',
        ),
        migrations.RemoveField(
            model_name='school',
            name='established_date',
        ),
        migrations.RemoveField(
            model_name='trainingcenter',
            name='director',
        ),
        migrations.RemoveField(
            model_name='trainingcenter',
            name='established_date',
        ),
        migrations.RemoveField(
            model_name='university',
            name='established_date',
        ),
        migrations.RemoveField(
            model_name='university',
            name='rector',
        ),
    ]
